using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WAES.BEN.TEST.SERVER.Models
{
    public enum StringComparisonResult
    {
        Unknown,

        /// <summary>
        /// The strings are equal in both size and content
        /// </summary>
        Equal,

        /// <summary>
        /// The strings are not equal in size
        /// </summary>
        NotOfEqualSize,

        /// <summary>
        /// The strings are of equal size, but might have differences in content
        /// </summary>
        EqualSize,

    }

    public class ComparisonResultModel
    {
        #region ctor

        public ComparisonResultModel()
        {
        }

        #endregion

        #region class properties

        /// <summary>
        /// Gets or sets the overall result of the comparison
        /// </summary>
        public StringComparisonResult Result { get; set; }

        /// <summary>
        /// Gets or sets the dictionary of differences between the two strings,
        /// in which key is the start index of the diff and value is the offset (char length) of the difference  
        /// </summary>
        public Dictionary<int,int> Diff { get; set; }

        /// <summary>
        /// Gets or sets an info generated by the comparison
        /// </summary>
        public string Info { get; set; }

        #endregion

    }
}